# Generated by Django 5.0.2 on 2025-03-22 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Họ tên')),
                ('gender', models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], max_length=10, verbose_name='Giới tính')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('image_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL ảnh')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Ảnh')),
                ('expanded', models.BooleanField(default=False)),
                ('generation_level', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Thành viên',
                'verbose_name_plural': 'Thành viên',
            },
        ),
        migrations.CreateModel(
            name='ParentChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('blood', 'Con đẻ'), ('adopted', 'Con nuôi')], default='blood', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relations', to='family.person')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_relations', to='family.person')),
            ],
            options={
                'verbose_name': 'Quan hệ cha mẹ - con',
                'verbose_name_plural': 'Quan hệ cha mẹ - con',
            },
        ),
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marriage_type', models.CharField(choices=[('married', 'Đã kết hôn'), ('divorced', 'Đã ly hôn')], default='married', max_length=20)),
                ('marriage_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('spouse1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marriages_as_spouse1', to='family.person')),
                ('spouse2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marriages_as_spouse2', to='family.person')),
            ],
            options={
                'verbose_name': 'Hôn nhân',
                'verbose_name_plural': 'Hôn nhân',
            },
        ),
        migrations.CreateModel(
            name='Sibling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('blood', 'Anh chị em ruột'), ('half', 'Anh chị em cùng cha/mẹ'), ('step', 'Anh chị em kết')], default='blood', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sibling_relations1', to='family.person')),
                ('person2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sibling_relations2', to='family.person')),
            ],
            options={
                'verbose_name': 'Quan hệ anh chị em',
                'verbose_name_plural': 'Quan hệ anh chị em',
            },
        ),
    ]
