# Generated by Django 5.0.2 on 2025-03-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_alter_person_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày sinh'),
        ),
        migrations.AddField(
            model_name='person',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày mất'),
        ),
        migrations.AddField(
            model_name='person',
            name='family_rank',
            field=models.CharField(blank=True, choices=[('1', 'Con trưởng'), ('2', 'Con thứ hai'), ('3', 'Con thứ ba'), ('4', 'Con thứ tư'), ('5', 'Con thứ năm'), ('other', 'Khác')], max_length=10, null=True, verbose_name='Thứ bậc trong gia đình'),
        ),
        migrations.AddField(
            model_name='person',
            name='permanent_address',
            field=models.TextField(blank=True, null=True, verbose_name='Địa chỉ thường trú'),
        ),
        migrations.AddField(
            model_name='person',
            name='year_of_birth',
            field=models.IntegerField(blank=True, null=True, verbose_name='Năm sinh'),
        ),
        migrations.AddField(
            model_name='person',
            name='year_of_death',
            field=models.IntegerField(blank=True, null=True, verbose_name='Năm mất'),
        ),
    ]
