# Generated by Django 5.0.2 on 2025-04-12 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0003_person_date_of_birth_person_date_of_death_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='year_of_birth',
        ),
        migrations.RemoveField(
            model_name='person',
            name='year_of_death',
        ),
    ]
