# Generated by Django 5.0.2 on 2025-04-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0004_remove_person_year_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='generation_level',
            field=models.IntegerField(default=1, verbose_name='Thế hệ thứ'),
        ),
    ]
