# Generated by Django 5.0.2 on 2025-05-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0005_alter_person_generation_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='person_images/', verbose_name='Ảnh'),
        ),
    ]
