# Generated by Django 5.0.2 on 2025-05-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('images', models.JSONField(default=list, verbose_name='Danh sách ảnh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái')),
            ],
            options={
                'verbose_name': 'Trang chủ',
                'verbose_name_plural': 'Trang chủ',
                'ordering': ['-created_at'],
            },
        ),
    ]
